"""
OMP 配置管理器 - GUI 版
========================
可视化查看和修改所有 OMP 配置项，带中文说明
双击行可编辑，弹窗带详细说明
"""

import subprocess
import json
import os
import tkinter as tk
from tkinter import ttk, messagebox

CONFIG_DESC_ZH = {
    # 核心设置
    "shellPath": "Shell 路径：OMP 执行命令时使用的终端程序",
    "autoResume": "自动恢复会话：自动恢复当前目录的上次会话",
    "colorBlindMode": "色弱模式：用蓝色代替绿色显示 diff 新增内容",
    "symbolPreset": "符号风格：图标和特殊字符的显示样式",
    "repeatToolDescriptions": "完整工具描述：在系统提示中渲染完整工具描述而非简名",
    "includeModelInPrompt": "显示当前模型：在系统提示中显示 AI 使用的模型名称",
    "personality": "AI 回复风格：渲染到系统提示的个性块",
    "theme.dark": "暗色主题：终端深色背景时使用的主题",
    "theme.light": "亮色主题：终端浅色背景时使用的主题",
    "display.showTokenUsage": "显示 Token 消耗：在 AI 回复后显示本轮 token 用量",
    "display.tabWidth": "Tab 宽度：代码中 tab 字符的显示宽度",
    "display.shimmer": "加载动画：等待/加载时的动画风格",
    "display.smoothStreaming": "平滑输出：流式输出时平滑显示文字",
    "showHardwareCursor": "显示硬件光标：IME 输入法支持",
    "terminal.showImages": "终端显示图片：在终端内渲染图片",
    "images.blockImages": "阻止图片发送：禁止向 LLM 发送图片",
    "images.autoResize": "自动压缩图片：将大图片压缩到 2000x2000 以提高模型兼容性",
    "tui.maxInlineImageColumns": "TUI 内联图片最大列数",
    "tui.maxInlineImageRows": "TUI 内联图片最大行数",
    "tui.maxInlineImages": "TUI 最多内联显示的图片数",
    "tui.textSizing": "TUI 文字缩放：Kitty 终端中 H1 标题 2x 缩放",
    "tui.hyperlinks": "TUI 超链接：路径和 URL 的终端原生可点击打开",
    "readLineNumbers": "显示行号：read 工具输出默认带行号",
    "readHashLines": "快照标签：read 工具输出包含快照标签和行号",
    "statusLine.preset": "状态栏预设：预设的状态栏样式",
    "statusLine.separator": "状态栏分隔符：各模块之间的分隔符样式",
    "statusLine.sessionAccent": "会话名高亮：用会话名称颜色装饰边框和状态栏",
    "statusLine.showHookStatus": "显示 Hook 状态：在状态栏下方显示 Hook 消息",
    "statusLine.transparent": "状态栏透明：使用终端默认背景而非主题背景",
    "statusLine.leftSegments": "状态栏左侧模块：自定义左侧显示项",
    "statusLine.rightSegments": "状态栏右侧模块：自定义右侧显示项",
    "statusLine.segmentOptions": "状态栏模块选项：各模块的具体配置",
    "modelRoles": "模型角色分配：不同用途使用的模型",
    "cycleOrder": "模型切换顺序：Ctrl+P 循环切换的模型顺序",
    "defaultThinkingLevel": "默认思考级别：AI 思考深度",
    "hideThinkingBlock": "隐藏思考块：不在回复中显示 AI 的推理过程",
    "temperature": "温度：采样随机性（0=确定，1=创意，-1=默认）",
    "topP": "核采样：累积概率截断",
    "topK": "Top-K：只从概率最高的 K 个 token 中采样",
    "minP": "最小概率：最低概率阈值",
    "presencePenalty": "存在惩罚：对已出现 token 的惩罚",
    "repetitionPenalty": "重复惩罚：对重复 token 的惩罚",
    "serviceTier": "服务层级：处理优先级提示",
    "thinkingBudgets.minimal": "思考预算-最简：minimal 级别的 token 预算",
    "thinkingBudgets.low": "思考预算-低：low 级别的 token 预算",
    "thinkingBudgets.medium": "思考预算-中：medium 级别的 token 预算",
    "thinkingBudgets.high": "思考预算-高：high 级别的 token 预算",
    "thinkingBudgets.xhigh": "思考预算-最高：xhigh 级别的 token 预算",
    "tools.approvalMode": "审批模式：yolo=自动 / write=部分询问 / always-ask=全部询问",
    "tools.artifactSpillThreshold": "输出溢出阈值：超过此 KB 的输出保存为文件",
    "tools.artifactTailBytes": "尾部保留字节：溢出时保留的尾部字节数",
    "tools.artifactHeadBytes": "头部保留字节：溢出时保留的头部字节数（0=只保留尾部）",
    "tools.artifactTailLines": "尾部保留行数：溢出时保留的尾部行数",
    "tools.outputMaxColumns": "输出最大列宽：单行输出的字节上限",
    "tools.intentTracing": "工具意图追踪：AI 调用工具前先描述意图",
    "tools.maxTimeout": "工具最大超时：所有工具的全局超时上限",
    "tools.discoveryMode": "工具发现模式：通过发现工具按需暴露工具",
    "tools.essentialOverride": "核心工具覆盖：覆盖始终加载的工具（默认 read/bash/edit）",
    "search.enabled": "启用搜索工具：代码内容搜索",
    "search.contextBefore": "搜索上文行数：匹配结果前显示几行上下文",
    "search.contextAfter": "搜索下文行数：匹配结果后显示几行上下文",
    "find.enabled": "启用文件查找工具：按文件名搜索",
    "edit.mode": "编辑模式：replace/patch/hashline/apply_patch",
    "edit.fuzzyMatch": "模糊匹配：编辑时容忍空白差异",
    "edit.fuzzyThreshold": "模糊匹配阈值：相似度要求（0-1）",
    "edit.streamingAbort": "编辑流中断：patch 预览失败时中断流式输出",
    "edit.blockAutoGenerated": "阻止自动生成文件编辑：禁止编辑 protobuf/swagger 等生成文件",
    "lsp.enabled": "启用 LSP 工具：语言服务器协议",
    "lsp.formatOnWrite": "写后格式化：写入代码后自动格式化",
    "lsp.diagnosticsOnWrite": "写后诊断：写入代码后返回 LSP 诊断信息",
    "lsp.diagnosticsOnEdit": "编辑后诊断：编辑代码后返回 LSP 诊断信息",
    "lsp.diagnosticsDeduplicate": "诊断去重：抑制已显示过的重复诊断",
    "lsp.lazy": "延迟启动：首次使用时启动语言服务器",
    "read.defaultLimit": "Read 默认行数：不指定限制时默认读取的行数",
    "read.summarize.enabled": "代码摘要：读取代码时返回结构摘要而非全文",
    "read.summarize.prose": "文本摘要：对 Markdown 和纯文本也返回结构摘要",
    "read.summarize.minBodyLines": "摘要最小正文：少于此行数的正文不折叠",
    "read.summarize.minCommentLines": "摘要最小注释：少于此行数的注释不折叠",
    "read.summarize.minTotalLines": "摘要最小行数：少于此行数的文件直接全文读取",
    "read.summarize.unfoldUntil": "展开到行数：BFS 展开折叠内容直到至少这么多行",
    "read.summarize.unfoldLimit": "展开最大行数：展开时的硬上限",
    "read.toolResultPreview": "内联预览：在对话中内联显示 read 结果",
    "bash.enabled": "启用 Bash 工具：允许执行 shell 命令",
    "bash.autoBackground.enabled": "自动后台化：长运行 bash 命令自动后台执行",
    "bash.autoBackground.thresholdMs": "后台化阈值：超过此毫秒的命令自动后台化",
    "bashInterceptor.enabled": "命令拦截：阻止用 bash 替代专用工具",
    "retry.enabled": "启用重试：API 出错时自动重试",
    "retry.maxRetries": "最大重试次数",
    "retry.baseDelayMs": "重试基础延迟：两次重试间的基础等待毫秒数",
    "retry.maxDelayMs": "重试最大延迟：两次重试间的最大等待毫秒数",
    "retry.modelFallback": "模型降级：API 失败时自动切换到备用模型",
    "retry.fallbackChains": "降级链：模型失败时的备用链配置",
    "retry.fallbackRevertPolicy": "恢复策略：降级后何时切回主模型",
    "compaction.enabled": "自动压缩：上下文过大时自动压缩历史",
    "compaction.strategy": "压缩策略：context-full/auto-handoff/surgical/snapcompact/off",
    "compaction.thresholdPercent": "压缩阈值百分比：上下文占用百分比触发压缩",
    "compaction.thresholdTokens": "压缩阈值 Token：固定 token 数触发压缩（覆盖百分比）",
    "compaction.reserveTokens": "预留 Token：为 AI 回复预留的 token 数量",
    "compaction.keepRecentTokens": "保留最近 Token：始终保留的最近对话 token 数",
    "compaction.autoContinue": "自动继续：压缩后自动继续对话",
    "compaction.remoteEnabled": "远程压缩：使用远程压缩端点而非本地摘要",
    "compaction.remoteEndpoint": "远程压缩端点：远程压缩服务的 URL",
    "compaction.handoffSaveToDisk": "交接文档保存：将自动交接文档保存到文件",
    "compaction.idleEnabled": "空闲压缩：空闲时自动压缩上下文",
    "compaction.idleThresholdTokens": "空闲压缩阈值：触发空闲压缩的 token 数",
    "compaction.idleTimeoutSeconds": "空闲等待时间：空闲多少秒后触发压缩",
    "compaction.supersedeReads": "缓存感知：删除同一文件的旧 read 结果",
    "snapcompact.systemPrompt": "系统提示图片化：将系统提示渲染为 PNG 图片（实验性，节省 token）",
    "snapcompact.toolResults": "工具结果图片化：将大工具结果渲染为 PNG 图片（实验性）",
    "branchSummary.enabled": "分支总结：离开分支时提示总结",
    "branchSummary.reserveTokens": "分支总结预留：分支总结时预留的 token 数",
    "loop.mode": "循环模式：/loop 迭代之间的行为",
    "steeringMode": "排队消息处理：AI 工作时如何处理排队消息",
    "followUpMode": "后续消息处理：一轮完成后如何处理后续消息",
    "interruptMode": "中断模式：中断消息如何影响工具执行",
    "doubleEscapeAction": "双 Esc 动作：编辑器为空时连按两次 Esc 的行为",
    "treeFilterMode": "会话树过滤：打开会话树时的默认过滤模式",
    "autocompleteMaxVisible": "自动补全最大显示：下拉菜单最多显示的项目数",
    "memory.backend": "记忆后端：off/local/mnemopi/hindsight",
    "contextPromotion.enabled": "上下文溢出升级：溢出时升级到大上下文模型而非压缩",
    "mcp.discoveryMode": "MCP 自动发现：通过发现工具按需暴露 MCP 工具",
    "mcp.enableProjectConfig": "启用项目 MCP 配置：加载项目目录下的 mcp.json",
    "mcp.discoveryDefaultServers": "始终显示的 MCP 服务器：发现模式下始终可见的服务器",
    "mcp.notifications": "MCP 通知：将 MCP 资源更新注入对话",
    "mcp.notificationDebounceMs": "MCP 通知防抖：MCP 更新注入的防抖毫秒数",
    "browser.enabled": "启用浏览器工具：自动化网页操作",
    "browser.headless": "无头浏览器：不显示浏览器界面",
    "browser.screenshotDir": "截图保存目录：浏览器截图的存储位置",
    "web_search.enabled": "启用 Web 搜索工具",
    "task.eager": "积极委派：鼓励 AI 将工作委派给子代理",
    "task.maxConcurrency": "子代理最大并发数",
    "task.maxRecursionDepth": "子代理最大递归深度",
    "task.batch": "批量子代理：一次调用派生多个独立子代理",
    "task.enableLsp": "子代理使用 LSP：允许子代理使用 lsp 工具",
    "task.isolation.mode": "子代理隔离模式：none/auto（隔离文件系统）",
    "task.isolation.merge": "子代理合并方式：patch 应用或 branch 合并",
    "task.isolation.commits": "子代理提交风格：generic 通用或 AI 生成",
    "task.maxRuntimeMs": "子代理最大运行时间：毫秒（0=不限制）",
    "task.agentIdleTtlMs": "子代理空闲 TTL：空闲子代理存活时间",
    "task.softRequestBudget": "子代理请求预算：每个子代理的最大 API 请求数",
    "task.disabledAgents": "禁用子代理：禁用的子代理类型列表",
    "task.agentModelOverrides": "子代理模型覆盖：各子代理的专属模型",
    "task.showResolvedModelBadge": "显示子代理模型：在任务组件中显示实际使用的模型",
    "todo.enabled": "启用 Todo 工具：任务跟踪",
    "todo.eager": "自动创建 Todo：首次消息后自动创建任务列表",
    "todo.reminders": "Todo 提醒：完成前提醒 AI 完成任务",
    "tasks.todoClearDelay": "Todo 清理延迟：完成或放弃的 todo 延迟多少秒后清除",
    "skills.enabled": "启用 Skills：加载技能定义",
    "skills.enableSkillCommands": "技能命令：将 Skills 注册为 /skill:name 命令",
    "skills.enableCodexUser": "加载 Codex 用户技能",
    "skills.enableClaudeUser": "加载 Claude 用户技能",
    "skills.enableClaudeProject": "加载 Claude 项目技能",
    "skills.enablePiUser": "加载 Pi 用户技能",
    "skills.enablePiProject": "加载 Pi 项目技能",
    "skills.customDirectories": "自定义技能目录",
    "skills.ignoredSkills": "忽略的技能列表",
    "skills.includeSkills": "包含的技能过滤列表",
    "stt.enabled": "语音输入：启用麦克风语音转文字",
    "stt.language": "语音识别语言：zh=中文，en=英文",
    "stt.modelName": "Whisper 模型大小：越大越准但越慢",
    "ttsr.enabled": "启用 TTSR：流式输出匹配规则时中断 AI",
    "ttsr.contextMode": "TTSR 触发模式：触发时对部分输出的处理",
    "ttsr.interruptMode": "TTSR 中断模式：何时中断流式输出",
    "ttsr.repeatMode": "TTSR 重复模式：规则可重复触发的方式",
    "ttsr.repeatGap": "TTSR 重复间隔：规则再次触发前需间隔的消息数",
    "ttsr.builtinRules": "TTSR 内置规则：加载默认规则",
    "ttsr.disabledRules": "TTSR 禁用规则：忽略的特定规则名称",
    "startup.quiet": "静默启动：跳过欢迎界面",
    "startup.checkUpdate": "检查更新：启动时检查新版本",
    "startup.setupWizard": "启动向导：显示新增的引导步骤",
    "marketplace.autoUpdate": "插件自动更新：启动时检查插件更新",
    "collapseChangelog": "精简日志：更新后显示压缩的变更日志",
    "completion.notify": "完成通知：AI 完成任务后通知",
    "ask.notify": "询问通知：AI 等待输入时通知",
    "ask.timeout": "询问超时：AI 提问后自动选择推荐选项的秒数",
    "emojiAutocomplete": "Emoji 自动补全",
    "magicKeywords.enabled": "魔法关键词：启用 ultrathink/orchestrate/workflowz",
    "magicKeywords.ultrathink": "ultrathink 关键词：启用最大自动思考",
    "magicKeywords.orchestrate": "orchestrate 关键词：启用多代理编排",
    "magicKeywords.workflow": "workflowz 关键词：启用评估工作流",
    "secrets.enabled": "Secret 混淆：发送给 AI 前混淆敏感信息",
    "plan.enabled": "启用计划模式：执行前先输出规划",
    "goal.enabled": "启用目标模式：控制 token 预算和目标",
    "goal.statusInFooter": "目标状态显示：在状态栏显示 token 预算",
    "goal.continuationModes": "目标自动继续：哪些模式下目标可自动继续",

    # 认证
    "auth.broker.url": "认证代理 URL",
    "auth.broker.token": "认证代理 Token",

    # 电源管理
    "power.preventIdleSleep": "保持系统唤醒：会话打开时阻止空闲睡眠 (caffeinate -i)",
    "power.preventSystemSleep": "阻止系统睡眠：接交流电时阻止所有系统睡眠 (caffeinate -s)",
    "power.declareUserActive": "声明用户活跃：保持屏幕常亮 (caffeinate -u)",
    "power.preventDisplaySleep": "阻止屏幕睡眠：会话打开时阻止屏幕空闲睡眠 (caffeinate -d)",

    # 模型管理
    "modelTags": "模型标签：给模型设置别名",
    "modelProviderOrder": "模型提供商排序",
    "fastModeScope": "/fast 模式作用域：both=所有提供商 / openai / claude",

    # 粘贴
    "paste.largeMenuThreshold": "大粘贴菜单阈值：粘贴达此行数时弹出菜单（代码块/XML/保存文件），0=禁用",

    # 协作 & 分享
    "collab.relayUrl": "协作中继 URL：/collab 使用的中继服务器",
    "collab.displayName": "协作显示名称",
    "share.serverUrl": "分享服务器 URL：/share 分享的查看/上传服务器",
    "share.redactSecrets": "分享前混淆密钥：/share 快照上传前混淆敏感信息",

    # 上下文压缩增强
    "compaction.dropUseless": "丢弃无用结果：剪除标记为无用的工具结果（无匹配、超时等）",

    # SnapCompact
    "snapcompact.shape": "SnapCompact 框架形状",
    # 认证
    "auth.broker.url": "认证代理 URL",
    "auth.broker.token": "认证代理 Token",
    # 电源管理
    "power.preventIdleSleep": "保持系统唤醒：会话打开时阻止空闲睡眠",
    "power.preventSystemSleep": "阻止系统睡眠：接交流电时阻止所有睡眠",
    "power.declareUserActive": "声明用户活跃：保持屏幕常亮",
    "power.preventDisplaySleep": "阻止屏幕睡眠：会话打开时阻止屏幕睡眠",
    # 模型管理
    "modelTags": "模型标签：给模型设置别名",
    "modelProviderOrder": "模型提供商排序",
    "fastModeScope": "/fast 模式作用域",
    # 粘贴
    "paste.largeMenuThreshold": "大粘贴菜单阈值",
    # 协作 & 分享
    "collab.relayUrl": "协作中继 URL",
    "collab.displayName": "协作显示名称",
    "share.serverUrl": "分享服务器 URL",
    "share.redactSecrets": "分享前混淆密钥",
    # 上下文压缩增强
    "compaction.dropUseless": "丢弃无用工具结果",
    # 记忆系统
    "memories.enabled": "启用记忆系统",
    "memories.maxRolloutsPerStartup": "每次启动最大记忆展开次数",
    "memories.maxRolloutAgeDays": "记忆展开最大存活天数",
    "memories.minRolloutIdleHours": "最小空闲小时后展开记忆",
    "memories.threadScanLimit": "线程扫描上限",
    "memories.maxRawMemoriesForGlobal": "全局搜索最大原始记忆数",
    "memories.stage1Concurrency": "阶段1并发数",
    "memories.stage1LeaseSeconds": "阶段1租约秒数",
    "memories.stage1RetryDelaySeconds": "阶段1重试延迟秒数",
    "memories.phase2LeaseSeconds": "阶段2租约秒数",
    "memories.phase2RetryDelaySeconds": "阶段2重试延迟秒数",
    "memories.phase2HeartbeatSeconds": "阶段2心跳秒数",
    "memories.rolloutPayloadPercent": "展开负载百分比",
    "memories.phase1InputTokenLimit": "阶段1输入 token 限制",
    "memories.fallbackTokenLimit": "回退 token 限制",
    "memories.summaryInjectionTokenLimit": "摘要注入 token 限制",
    # Mnemopi 本地记忆
    "mnemopi.dbPath": "Mnemopi SQLite 数据库路径",
    "mnemopi.bank": "共享库基础名称",
    "mnemopi.scoping": "Mnemopi 作用域",
    "mnemopi.embeddingVariant": "嵌入模型变体",
    "mnemopi.autoRecall": "Mnemopi 自动回忆",
    "mnemopi.autoRetain": "Mnemopi 自动保留",
    "mnemopi.polyphonicRecall": "Mnemopi 多声部回忆",
    "mnemopi.enhancedRecall": "Mnemopi 增强回忆",
    "mnemopi.noEmbeddings": "Mnemopi 禁用嵌入",
    "mnemopi.embeddingModel": "Mnemopi 嵌入模型 ID",
    "mnemopi.embeddingApiUrl": "Mnemopi 嵌入 API 端点",
    "mnemopi.embeddingApiKey": "Mnemopi 嵌入 API 密钥",
    "mnemopi.llmMode": "Mnemopi LLM 模式",
    "mnemopi.llmBaseUrl": "Mnemopi 远程 LLM 端点",
    "mnemopi.llmApiKey": "Mnemopi 远程 LLM 密钥",
    "mnemopi.llmModel": "Mnemopi 远程 LLM 模型名",
    "mnemopi.retainEveryNTurns": "Mnemopi 每 N 轮自动保留",
    "mnemopi.recallLimit": "Mnemopi 回忆条数上限",
    "mnemopi.recallContextTurns": "Mnemopi 回忆上下文轮数",
    "mnemopi.recallMaxQueryChars": "Mnemopi 回忆查询最大字符数",
    "mnemopi.injectionTokenLimit": "Mnemopi 注入 token 限制",
    "mnemopi.debug": "Mnemopi 调试模式",
    # Hindsight 远程记忆
    "hindsight.apiUrl": "Hindsight 服务器 URL",
    "hindsight.apiToken": "Hindsight API Token",
    "hindsight.bankId": "Hindsight 记忆库 ID",
    "hindsight.bankIdPrefix": "Hindsight 记忆库 ID 前缀",
    "hindsight.scoping": "Hindsight 作用域",
    "hindsight.bankMission": "Hindsight 记忆库使命提示",
    "hindsight.retainMission": "Hindsight 保留使命提示",
    "hindsight.autoRecall": "Hindsight 自动回忆",
    "hindsight.autoRetain": "Hindsight 自动保留",
    "hindsight.retainMode": "Hindsight 保留模式",
    "hindsight.retainEveryNTurns": "Hindsight 每 N 轮保留",
    "hindsight.retainOverlapTurns": "Hindsight 保留重叠轮数",
    "hindsight.retainContext": "Hindsight 保留上下文",
    "hindsight.recallBudget": "Hindsight 回忆预算",
    "hindsight.recallMaxTokens": "Hindsight 回忆最大 token",
    "hindsight.recallContextTurns": "Hindsight 回忆上下文轮数",
    "hindsight.recallMaxQueryChars": "Hindsight 回忆查询最大字符",
    "hindsight.recallTypes": "Hindsight 回忆类型",
    "hindsight.debug": "Hindsight 调试",
    "hindsight.mentalModelsEnabled": "Hindsight 心智模型",
    "hindsight.mentalModelAutoSeed": "Hindsight 心智模型自动种子",
    "hindsight.mentalModelRefreshIntervalMs": "Hindsight 心智模型刷新间隔",
    "hindsight.mentalModelMaxRenderChars": "Hindsight 心智模型最大渲染字符",
    # 自动学习
    "autolearn.enabled": "自动学习",
    "autolearn.autoContinue": "自动学习自动继续",
    "autolearn.minToolCalls": "自动学习最少工具调用数",
    # Bash 增强
    "bashInterceptor.patterns": "Bash 拦截规则",
    "bash.stripTrailingHeadTail": "Bash 剥离 head/tail",
    # Shell 压缩
    "shellMinimizer.enabled": "Shell 输出压缩",
    "shellMinimizer.settingsPath": "Shell 压缩设置路径",
    "shellMinimizer.only": "Shell 压缩白名单",
    "shellMinimizer.except": "Shell 压缩排除",
    "shellMinimizer.maxCaptureBytes": "Shell 压缩最大捕获字节数",
    "shellMinimizer.sourceOutlineLevel": "Shell 压缩源码大纲",
    "shellMinimizer.legacyFilters": "Shell 压缩旧版过滤器",
    # Eval
    "eval.py": "允许 eval 执行 Python",
    "eval.js": "允许 eval 执行 JavaScript",
    # Python
    "python.kernelMode": "Python 内核模式",
    "python.interpreter": "Python 解释器路径",
    # 工具审批增强
    "tools.approval": "逐工具审批策略",
    # Todo 增强
    "todo.reminders.max": "Todo 提醒最大次数",
    "todo.eager": "Todo 自动创建积极程度",
    # AST 工具
    "astGrep.enabled": "启用 ast_grep",
    "astEdit.enabled": "启用 ast_edit",
    # 工具扩展
    "renderMermaid.enabled": "启用 render_mermaid",
    "debug.enabled": "启用 debug 调试",
    "speechgen.enabled": "启用 speechgen 语音合成",
    "inspect_image.enabled": "启用 inspect_image",
    "checkpoint.enabled": "启用 checkpoint",
    "fetch.enabled": "启用 fetch URL",
    "vault.enabled": "启用 vault Obsidian",
    "github.enabled": "启用 github",
    "github.cache.enabled": "GitHub 缓存",
    "github.cache.softTtlSec": "GitHub 缓存软过期",
    "github.cache.hardTtlSec": "GitHub 缓存硬过期",
    # 异步
    "async.enabled": "启用异步",
    "async.maxJobs": "最大后台任务数",
    "async.pollWaitDuration": "Poll 等待策略",
    # IRC
    "irc.timeoutMs": "IRC 等待默认超时",
    # 工具发现
    "tools.discoveryMode": "工具发现模式",
    # Skills
    "skills.enableAgentsUser": "加载 Agents 用户技能",
    "skills.enableAgentsProject": "加载 Agents 项目技能",
    # Commands
    "commands.enableClaudeUser": "加载 Claude 用户命令",
    "commands.enableClaudeProject": "加载 Claude 项目命令",
    "commands.enableOpencodeUser": "加载 Opencode 用户命令",
    "commands.enableOpencodeProject": "加载 Opencode 项目命令",
    # 提供商配置
    "providers.webSearch": "Web 搜索首选提供商",
    "providers.image": "图片生成首选提供商",
    "providers.tts": "TTS 后端",
    "tts.localModel": "本地 TTS 模型",
    "tts.localVoice": "本地 TTS 语音",
    # 语音输出
    "speech.enabled": "语音输出",
    "speech.mode": "语音模式",
    "speech.voice": "语音输出语音",
    # 提供商模型
    "providers.tinyModel": "会话标题模型来源",
    "providers.tinyModelDevice": "TinyModel 设备",
    "providers.tinyModelDtype": "TinyModel 精度",
    "providers.memoryModel": "记忆模型来源",
    "providers.autoThinkingModel": "自动思考模型来源",
    "providers.kimiApiFormat": "Kimi Code API 格式",
    "providers.openaiWebsockets": "OpenAI WebSocket 策略",
    "providers.openrouterVariant": "OpenRouter 路由变体",
    "providers.fetch": "URL 读取后端优先级",
    # Provider 缓存
    "provider.appendOnlyContext": "Provider 追加缓存",
    # Codex 重置
    "codexResets.autoRedeem": "Codex 自动兑换",
    "codexResets.minBlockedMinutes": "Codex 自动兑换最小阻塞分钟",
    "codexResets.keepCredits": "Codex 保留信用额度",
    # Exa 搜索
    "exa.enabled": "Exa 搜索总开关",
    "exa.enableSearch": "Exa 基本/深度/代码搜索",
    "exa.enableResearcher": "Exa 深度研究工具",
    "exa.enableWebsets": "Exa 数据集管理",
    # SearXNG
    "searxng.endpoint": "SearXNG 实例 URL",
    "searxng.token": "SearXNG Token",
    "searxng.basicUsername": "SearXNG 用户名",
    "searxng.basicPassword": "SearXNG 密码",
    "searxng.categories": "SearXNG 搜索分类",
    "searxng.language": "SearXNG 搜索语言",
    # Commit
    "commit.mapReduceEnabled": "Commit map-reduce",
    "commit.mapReduceMinFiles": "Commit map-reduce 最小文件数",
    "commit.mapReduceMaxFileTokens": "Commit map-reduce 单文件最大 token",
    "commit.mapReduceTimeoutMs": "Commit map-reduce 超时",
    "commit.mapReduceMaxConcurrency": "Commit map-reduce 最大并发",
    "commit.changelogMaxDiffChars": "Changelog 最大差异字符",
    # Auto QA
    "dev.autoqa": "自动 QA",
    "dev.autoqaPush.endpoint": "Auto QA 报告端点",
    "dev.autoqaPush.token": "Auto QA Token",
    "dev.autoqa.consent": "Auto QA 同意状态",
    # Browser
    "browser.cmux": "浏览器 cmux WKWebView",
    # 内部/高级
    "extensions": "已安装的扩展列表",
    "enabledModels": "已启用的模型列表",
    "disabledProviders": "已禁用的提供商列表",
    "disabledExtensions": "已禁用的扩展列表",
    "setupVersion": "安装版本号",
    # 工具增强
    "tools.abortOnFabricatedResult": "工具伪造中断：检测到 AI 伪造工具结果时立即停止",
    "tools.format": "工具暴露格式：auto=原生工具调用 / manual=内联暴露",
}

CATEGORY_GROUPS = {
    " 所有配置": None,
    " 核心设置": ["shellPath", "autoResume", "colorBlindMode", "symbolPreset", "repeatToolDescriptions", "includeModelInPrompt", "personality"],
    " 主题与外观": ["theme.dark", "theme.light", "display.showTokenUsage", "display.tabWidth", "display.shimmer", "display.smoothStreaming", "showHardwareCursor", "terminal.showImages", "images.blockImages", "images.autoResize", "tui.maxInlineImageColumns", "tui.maxInlineImageRows", "tui.maxInlineImages", "tui.textSizing", "tui.hyperlinks", "readLineNumbers", "readHashLines"],
    " 状态栏": ["statusLine.preset", "statusLine.separator", "statusLine.sessionAccent", "statusLine.showHookStatus", "statusLine.transparent", "statusLine.leftSegments", "statusLine.rightSegments", "statusLine.segmentOptions"],
    " 模型与 AI": ["modelRoles", "modelTags", "modelProviderOrder", "cycleOrder", "defaultThinkingLevel", "hideThinkingBlock", "temperature", "topP", "topK", "minP", "presencePenalty", "repetitionPenalty", "serviceTier", "fastModeScope", "thinkingBudgets.minimal", "thinkingBudgets.low", "thinkingBudgets.medium", "thinkingBudgets.high", "thinkingBudgets.xhigh"],
    " 工具通用": ["tools.abortOnFabricatedResult", "tools.format", "tools.approval", "tools.approvalMode", "tools.artifactSpillThreshold", "tools.artifactTailBytes", "tools.artifactHeadBytes", "tools.artifactTailLines", "tools.outputMaxColumns", "tools.intentTracing", "tools.maxTimeout", "tools.discoveryMode", "tools.essentialOverride"],
    " 搜索与编辑": ["search.enabled", "search.contextBefore", "search.contextAfter", "find.enabled", "edit.mode", "edit.fuzzyMatch", "edit.fuzzyThreshold", "edit.streamingAbort", "edit.blockAutoGenerated", "astGrep.enabled", "astEdit.enabled"],
    " LSP": ["lsp.enabled", "lsp.formatOnWrite", "lsp.diagnosticsOnWrite", "lsp.diagnosticsOnEdit", "lsp.diagnosticsDeduplicate", "lsp.lazy"],
    " Read": ["read.defaultLimit", "read.summarize.enabled", "read.summarize.prose", "read.summarize.minBodyLines", "read.summarize.minCommentLines", "read.summarize.minTotalLines", "read.summarize.unfoldUntil", "read.summarize.unfoldLimit", "read.toolResultPreview", "fetch.enabled"],
    " Bash": ["bash.enabled", "bash.autoBackground.enabled", "bash.autoBackground.thresholdMs", "bashInterceptor.enabled", "bashInterceptor.patterns", "bash.stripTrailingHeadTail"],
    " Shell 压缩": ["shellMinimizer.enabled", "shellMinimizer.settingsPath", "shellMinimizer.only", "shellMinimizer.except", "shellMinimizer.maxCaptureBytes", "shellMinimizer.sourceOutlineLevel", "shellMinimizer.legacyFilters"],
    " 重试与容错": ["retry.enabled", "retry.maxRetries", "retry.baseDelayMs", "retry.maxDelayMs", "retry.modelFallback", "retry.fallbackChains", "retry.fallbackRevertPolicy"],
    " 上下文管理": ["compaction.enabled", "compaction.strategy", "compaction.thresholdPercent", "compaction.thresholdTokens", "compaction.reserveTokens", "compaction.keepRecentTokens", "compaction.autoContinue", "compaction.remoteEnabled", "compaction.remoteEndpoint", "compaction.handoffSaveToDisk", "compaction.idleEnabled", "compaction.idleThresholdTokens", "compaction.idleTimeoutSeconds", "compaction.supersedeReads", "compaction.dropUseless"],
    " SnapCompact": ["snapcompact.systemPrompt", "snapcompact.toolResults", "snapcompact.shape"],
    " 分支与循环": ["branchSummary.enabled", "branchSummary.reserveTokens", "loop.mode"],
    " 交互模式": ["steeringMode", "followUpMode", "interruptMode", "doubleEscapeAction", "treeFilterMode", "autocompleteMaxVisible"],
    " 粘贴": ["paste.largeMenuThreshold"],
    " 记忆系统": ["memory.backend", "contextPromotion.enabled", "memories.enabled", "memories.maxRolloutsPerStartup", "memories.maxRolloutAgeDays", "memories.minRolloutIdleHours", "memories.threadScanLimit", "memories.maxRawMemoriesForGlobal", "memories.stage1Concurrency", "memories.stage1LeaseSeconds", "memories.stage1RetryDelaySeconds", "memories.phase2LeaseSeconds", "memories.phase2RetryDelaySeconds", "memories.phase2HeartbeatSeconds", "memories.rolloutPayloadPercent", "memories.phase1InputTokenLimit", "memories.fallbackTokenLimit", "memories.summaryInjectionTokenLimit"],
    " Mnemopi 本地记忆": ["mnemopi.dbPath", "mnemopi.bank", "mnemopi.scoping", "mnemopi.embeddingVariant", "mnemopi.autoRecall", "mnemopi.autoRetain", "mnemopi.polyphonicRecall", "mnemopi.enhancedRecall", "mnemopi.noEmbeddings", "mnemopi.embeddingModel", "mnemopi.embeddingApiUrl", "mnemopi.embeddingApiKey", "mnemopi.llmMode", "mnemopi.llmBaseUrl", "mnemopi.llmApiKey", "mnemopi.llmModel", "mnemopi.retainEveryNTurns", "mnemopi.recallLimit", "mnemopi.recallContextTurns", "mnemopi.recallMaxQueryChars", "mnemopi.injectionTokenLimit", "mnemopi.debug"],
    " Hindsight 远程记忆": ["hindsight.apiUrl", "hindsight.apiToken", "hindsight.bankId", "hindsight.bankIdPrefix", "hindsight.scoping", "hindsight.bankMission", "hindsight.retainMission", "hindsight.autoRecall", "hindsight.autoRetain", "hindsight.retainMode", "hindsight.retainEveryNTurns", "hindsight.retainOverlapTurns", "hindsight.retainContext", "hindsight.recallBudget", "hindsight.recallMaxTokens", "hindsight.recallContextTurns", "hindsight.recallMaxQueryChars", "hindsight.recallTypes", "hindsight.debug", "hindsight.mentalModelsEnabled", "hindsight.mentalModelAutoSeed", "hindsight.mentalModelRefreshIntervalMs", "hindsight.mentalModelMaxRenderChars"],
    " 自动学习": ["autolearn.enabled", "autolearn.autoContinue", "autolearn.minToolCalls"],
    " MCP & 网络": ["mcp.discoveryMode", "mcp.enableProjectConfig", "mcp.discoveryDefaultServers", "mcp.notifications", "mcp.notificationDebounceMs", "browser.enabled", "browser.headless", "browser.cmux", "browser.screenshotDir"],
    " Web 搜索": ["web_search.enabled", "exa.enabled", "exa.enableSearch", "exa.enableResearcher", "exa.enableWebsets", "searxng.endpoint", "searxng.token", "searxng.basicUsername", "searxng.basicPassword", "searxng.categories", "searxng.language"],
    " 任务与子代理": ["task.eager", "task.batch", "task.maxConcurrency", "task.enableLsp", "task.maxRecursionDepth", "task.isolation.mode", "task.isolation.merge", "task.isolation.commits", "task.maxRuntimeMs", "task.agentIdleTtlMs", "task.softRequestBudget", "task.disabledAgents", "task.agentModelOverrides", "task.showResolvedModelBadge"],
    " Todo & Skills": ["todo.enabled", "todo.eager", "todo.reminders", "todo.reminders.max", "tasks.todoClearDelay", "skills.enabled", "skills.enableSkillCommands", "skills.enableCodexUser", "skills.enableClaudeUser", "skills.enableClaudeProject", "skills.enablePiUser", "skills.enablePiProject", "skills.enableAgentsUser", "skills.enableAgentsProject", "skills.customDirectories", "skills.ignoredSkills", "skills.includeSkills"],
    " 语音输入": ["stt.enabled", "stt.language", "stt.modelName"],
    " 语音输出 & TTS": ["speech.enabled", "speech.mode", "speech.voice", "speechgen.enabled", "providers.tts", "tts.localModel", "tts.localVoice"],
    " TTSR 流规则": ["ttsr.enabled", "ttsr.contextMode", "ttsr.interruptMode", "ttsr.repeatMode", "ttsr.repeatGap", "ttsr.builtinRules", "ttsr.disabledRules"],
    " Eval & Python": ["eval.py", "eval.js", "python.kernelMode", "python.interpreter"],
    " 启动与通知": ["startup.quiet", "startup.checkUpdate", "startup.setupWizard", "marketplace.autoUpdate", "collapseChangelog", "completion.notify", "ask.notify", "ask.timeout"],
    " 异步 & IRC": ["async.enabled", "async.maxJobs", "async.pollWaitDuration", "irc.timeoutMs"],
    " 协作 & 分享": ["collab.relayUrl", "collab.displayName", "share.serverUrl", "share.redactSecrets"],
    " 认证 & 电源": ["auth.broker.url", "auth.broker.token", "power.preventIdleSleep", "power.preventSystemSleep", "power.declareUserActive", "power.preventDisplaySleep"],
    " Commands": ["commands.enableClaudeUser", "commands.enableClaudeProject", "commands.enableOpencodeUser", "commands.enableOpencodeProject"],
    " 提供商模型": ["providers.webSearch", "providers.image", "providers.tinyModel", "providers.tinyModelDevice", "providers.tinyModelDtype", "providers.memoryModel", "providers.autoThinkingModel", "providers.kimiApiFormat", "providers.openaiWebsockets", "providers.openrouterVariant", "providers.fetch", "provider.appendOnlyContext"],
    " Codex 重置": ["codexResets.autoRedeem", "codexResets.minBlockedMinutes", "codexResets.keepCredits"],
    " 工具扩展": ["renderMermaid.enabled", "debug.enabled", "inspect_image.enabled", "checkpoint.enabled", "vault.enabled", "github.enabled", "github.cache.enabled", "github.cache.softTtlSec", "github.cache.hardTtlSec"],
    " Commit": ["commit.mapReduceEnabled", "commit.mapReduceMinFiles", "commit.mapReduceMaxFileTokens", "commit.mapReduceTimeoutMs", "commit.mapReduceMaxConcurrency", "commit.changelogMaxDiffChars"],
    " Auto QA": ["dev.autoqa", "dev.autoqaPush.endpoint", "dev.autoqaPush.token", "dev.autoqa.consent"],
    " 其他": ["emojiAutocomplete", "magicKeywords.enabled", "magicKeywords.ultrathink", "magicKeywords.orchestrate", "magicKeywords.workflow", "secrets.enabled", "plan.enabled", "goal.enabled", "goal.statusInFooter", "goal.continuationModes"],
    " 内部/高级": ["extensions", "enabledModels", "disabledProviders", "disabledExtensions", "setupVersion"],
}
# 每个配置项的详细说明（面向业务人员）
HINT_TEXT = {
    # 核心
    "shellPath": "📌 这是 OMP 执行命令时使用的终端程序路径。\n 一般用 Git Bash 即可，保持默认不需要改。",
    "colorBlindMode": "📌 开启后，代码差异的「新增」部分用蓝色显示（而非绿色），方便色弱人群辨识。\n💡 默认已开启，建议保持。",
    "symbolPreset": "📌 图标和特殊字符的显示风格。\n💡 unicode=Unicode 字符，nerd= Nerd Font，ascii=纯 ASCII。",
    "autoResume": "📌 打开 OMP 时自动恢复当前目录的最后一次会话。\n💡 建议关闭，每次从新会话开始更干净。",
    "repeatToolDescriptions": "📌 开启后，系统提示中渲染完整工具描述而非简名列表。\n💡 一般不需要改。",
    "includeModelInPrompt": "📌 在系统提示中显示当前 AI 模型名称，让 agent 知道自己用的什么模型。\n💡 建议开启。",
    "personality": "📌 控制 AI 回复的风格。\n💡 default=默认，terse=简洁，chatty=健谈。",

    # 主题
    "theme.dark": " 终端深色背景时使用的配色主题。\n💡 可选值：titanium（钛色）、monokai、dracula 等。",
    "theme.light": "📌 终端浅色背景时使用的配色主题。\n💡 可选值：graphite、default 等。",
    "display.showTokenUsage": "📌 开启后，每次 AI 回复后会显示本轮消耗的 token 数量和费用。\n💡 开启可了解成本，关闭可节省屏幕空间。",
    "display.tabWidth": "📌 代码中 Tab 键的显示宽度（空格数）。\n💡 推荐 2-4 之间，2 更紧凑，4 更易读。",
    "display.shimmer": "📌 AI 思考/加载时的动画效果。\n 可选值：classic（经典）、dots（点阵）等。",
    "display.smoothStreaming": "📌 开启后，AI 的文字会平滑逐字显示，而非整段出现。\n 建议保持开启，阅读体验更好。",
    "showHardwareCursor": "📌 是否显示终端光标（中文输入法支持）。\n💡 建议开启。",
    "terminal.showImages": "📌 是否在终端内渲染图片。\n💡 建议开启。",
    "images.blockImages": "📌 是否禁止向 AI 发送图片。\n💡 建议关闭，让 AI 能看到图片。",
    "images.autoResize": "📌 自动将大图片压缩到 2000x2000 以内，提高模型兼容性。\n💡 建议开启。",
    "tui.maxInlineImageColumns": "📌 TUI 内联显示图片的最大列数。\n💡 默认 100。",
    "tui.maxInlineImageRows": "📌 TUI 内联显示图片的最大行数。\n💡 默认 20。",
    "tui.maxInlineImages": "📌 TUI 最多内联显示多少张图片。\n💡 默认 8。",
    "tui.textSizing": "📌 在 Kitty 终端中，H1 标题以 2x 比例渲染。\n💡 仅对 Kitty 终端有效。",
    "tui.hyperlinks": "📌 将路径和 URL 包装为终端原生可点击超链接。\n💡 auto=自动检测，off=关闭，always=强制。",
    "readLineNumbers": "📌 read 工具输出默认带行号。\n💡 建议关闭（hashline 模式下已有行号）。",
    "readHashLines": "📌 read 工具输出包含快照标签和行号，用于 hashline 编辑模式。\n💡 建议开启。",

    # 状态栏
    "statusLine.preset": "📌 状态栏的样式预设。\n💡 可选值：full（完整）、compact（紧凑）、minimal（极简）。",
    "statusLine.separator": " 状态栏各模块之间的分隔符样式。\n💡 可选值：powerline（带箭头）、pipe（竖线）、space（空格）。",
    "statusLine.sessionAccent": " 开启后，状态栏和边框会用会话名称的颜色高亮。\n 建议开启，方便区分多个会话。",
    "statusLine.showHookStatus": "📌 开启后，在状态栏下方显示钩子（hook）的执行状态。\n 一般不需要，关闭即可。",
    "statusLine.transparent": "📌 使用终端默认背景而非主题背景渲染状态栏。\n💡 开启后 powerline 端帽会消失。",
    "statusLine.leftSegments": "📌 自定义状态栏左侧显示模块。\n💡 数组类型，可添加/移除特定模块。",
    "statusLine.rightSegments": "📌 自定义状态栏右侧显示模块。\n💡 数组类型，可添加/移除特定模块。",
    "statusLine.segmentOptions": "📌 各状态栏模块的具体配置。\n💡 字典类型，每个 key 对应一个模块选项。",

    # 模型
    "modelRoles": " 不同场景使用不同的 AI 模型。\n💡 双击编辑可修改各角色对应的模型，一般不需要改。",
    "cycleOrder": "📌 按 Ctrl+P 时，模型循环切换的顺序。\n💡 默认 smol→default→slow，一般不需要改。",
    "defaultThinkingLevel": "📌 AI 思考的深度级别。\n💡 auto=自动选择，minimal=最简，low=低，medium=中等，high=深度，xhigh=极深。推荐 auto。",
    "hideThinkingBlock": "📌 开启后，AI 的推理过程不会显示在回复中。\n💡 建议关闭，方便了解 AI 的思考逻辑。",
    "temperature": "📌 控制 AI 回答的随机性。\n💡 0=最确定（保守），1=最随机（有创意），-1=让模型自己决定。推荐 -1。",
    "topP": "📌 控制 AI 从概率分布中采样的范围。\n💡 一般保持 -1（默认）即可，不用改。",
    "topK": " 控制 AI 只从概率最高的 K 个词中选择。\n💡 一般保持 -1（默认）即可，不用改。",
    "minP": "📌 控制 AI 采样的最低概率阈值。\n💡 一般保持 -1（默认）即可，不用改。",
    "presencePenalty": "📌 对已出现在文本中的 token 施加惩罚，鼓励多样性。\n💡 一般保持 -1（默认）。",
    "repetitionPenalty": "📌 对重复 token 施加惩罚，减少重复输出。\n💡 一般保持 -1（默认）。",
    "serviceTier": "📌 处理优先级提示。\n💡 none=不设置，priority=优先（Anthropic Opus fast）。",
    "thinkingBudgets.minimal": "📌 minimal 思考级别的 token 预算。\n💡 默认 1024。",
    "thinkingBudgets.low": "📌 low 思考级别的 token 预算。\n💡 默认 2048。",
    "thinkingBudgets.medium": "📌 medium 思考级别的 token 预算。\n💡 默认 8192。",
    "thinkingBudgets.high": "📌 high 思考级别的 token 预算。\n💡 默认 16384。",
    "thinkingBudgets.xhigh": "📌 xhigh 思考级别的 token 预算。\n💡 默认 32768。",

    # 工具通用
    "tools.abortOnFabricatedResult": "📌 检测到 AI 伪造工具结果时立即停止模型。\n💡 建议开启，避免 AI 继续伪造。",
    "tools.format": "📌 控制工具如何暴露给 AI 模型。\n💡 auto=原生工具调用（推荐），manual=内联暴露。",
    "tools.approvalMode": "📌 决定 AI 执行操作前是否需要你确认。\n💡 yolo=全自动，write=写操作前确认，always-ask=每次都确认。",
    "tools.artifactSpillThreshold": "📌 工具输出超过此值（KB）时，会保存为文件而非全部显示。\n💡 默认 50 KB，一般不需要改。",
    "tools.artifactTailBytes": "📌 溢出时保留的尾部字节数。\n💡 默认 20。",
    "tools.artifactHeadBytes": "📌 溢出时保留的头部字节数（0=只保留尾部）。\n💡 默认 20。",
    "tools.artifactTailLines": "📌 溢出时保留的尾部行数。\n💡 默认 500。",
    "tools.outputMaxColumns": "📌 单行输出的最大字节数，超出会被截断。\n💡 默认 768，一般不需要改。",
    "tools.intentTracing": " 开启后，AI 执行工具前会先描述意图。\n💡 建议开启，方便了解 AI 在做什么。",
    "tools.maxTimeout": "📌 所有工具的全局超时上限（秒）。\n💡 0=不限制。",
    "tools.discoveryMode": "📌 通过发现工具按需暴露工具，而非全部加载。\n💡 建议开启，节省 token。",
    "tools.essentialOverride": "📌 覆盖始终加载的核心工具（默认 read/bash/edit）。\n💡 留空使用默认。",

    # 搜索
    "search.enabled": "📌 是否启用代码内容搜索工具。\n💡 建议开启，否则 AI 无法搜索代码。",
    "search.contextBefore": "📌 搜索结果前显示几行上下文。\n💡 默认 1 行，一般不需要改。",
    "search.contextAfter": "📌 搜索结果后显示几行上下文。\n💡 默认 3 行，一般不需要改。",
    "find.enabled": "📌 是否启用按文件名搜索工具。\n💡 建议开启。",

    # 编辑
    "edit.mode": " 代码编辑工具的实现方式。\n💡 hashline 是最稳定的方式，一般不需要改。",
    "edit.fuzzyMatch": "📌 开启后，编辑代码时容忍空白字符差异。\n💡 建议开启，减少编辑失败。",
    "edit.fuzzyThreshold": "📌 模糊匹配的相似度阈值（0-1）。\n💡 0.95 表示 95% 相似才接受，建议保持。",
    "edit.streamingAbort": "📌 patch 预览失败时中断流式输出。\n💡 建议关闭，允许 AI 重试。",
    "edit.blockAutoGenerated": "📌 禁止编辑 protobuf/swagger/sqlc 等自动生成的文件。\n💡 建议开启。",
    "lsp.enabled": "📌 是否启用语言服务器协议（代码智能提示、语法检查）。\n💡 建议开启。",
    "lsp.formatOnWrite": "📌 写入代码后自动格式化。\n💡 建议关闭，让语言服务器处理格式化。",

    # LSP
    "lsp.diagnosticsOnWrite": "📌 写入代码后返回 LSP 诊断信息。\n💡 建议开启，及时发现错误。",
    "lsp.diagnosticsOnEdit": "📌 编辑代码后返回 LSP 诊断信息。\n💡 建议关闭（diagnosticsOnWrite 已覆盖）。",
    "lsp.diagnosticsDeduplicate": "📌 抑制已显示过的重复诊断，只显示新增或变化的。\n💡 建议开启。",
    "lsp.lazy": "📌 首次使用 LSP 或编辑匹配文件时才启动语言服务器。\n💡 建议开启，节省启动时间。",

    # Read
    "read.defaultLimit": "📌 不指定行数时，默认读取的行数。\n 默认 300 行，一般不需要改。",
    "read.summarize.enabled": "📌 读取代码时返回结构摘要而非全文。\n💡 建议开启，节省 token。",
    "read.summarize.prose": "📌 对 Markdown 和纯文本也返回结构摘要。\n💡 建议关闭，只对代码有意义。",
    "read.summarize.minBodyLines": "📌 少于此行数的正文不折叠。\n💡 默认 4。",
    "read.summarize.minCommentLines": "📌 少于此行数的注释不折叠。\n💡 默认 6。",
    "read.summarize.minTotalLines": "📌 少于此行数的文件直接全文读取，不做摘要。\n💡 默认 100 行，一般不需要改。",
    "read.summarize.unfoldUntil": "📌 BFS 展开折叠内容直到至少这么多可见行。\n💡 默认 50。",
    "read.summarize.unfoldLimit": "📌 展开时的硬上限，超过此行数停止展开。\n💡 默认 100。",
    "read.toolResultPreview": "📌 在对话中内联显示 read 结果而非摘要行。\n💡 建议关闭，节省空间。",

    # Bash
    "bash.enabled": "📌 是否允许执行 bash 命令。\n💡 建议开启，关闭后 AI 无法执行命令。",
    "bash.autoBackground.enabled": "📌 长运行 bash 命令自动后台执行，完成后返回结果。\n💡 适合需要几分钟的命令。",
    "bash.autoBackground.thresholdMs": "📌 超过此毫秒的命令自动后台化。\n💡 默认 5000（5 秒）。",
    "bashInterceptor.enabled": " 是否阻止用 bash 命令替代专用工具。\n💡 建议关闭。",

    # 重试
    "retry.enabled": "📌 API 出错时是否自动重试。\n💡 建议开启。",
    "retry.maxRetries": "📌 API 出错时最多重试几次。\n💡 默认 10。",
    "retry.baseDelayMs": "📌 两次重试间的基础等待毫秒数。\n💡 默认 500。",
    "retry.maxDelayMs": "📌 两次重试间的最大等待毫秒数。\n💡 默认 300000（5 分钟）。",
    "retry.modelFallback": "📌 API 失败时是否自动切换到备用模型。\n💡 建议开启，提高稳定性。",
    "retry.fallbackChains": "📌 模型失败时的备用链配置。\n💡 字典类型，每个 key 对应一个降级链。",
    "retry.fallbackRevertPolicy": "📌 降级后何时切回主模型。\n💡 cooldown-expiry=冷却期后恢复。",

    # 上下文
    "compaction.enabled": "📌 上下文太大时自动压缩历史记录。\n💡 建议开启，防止上下文溢出。",
    "compaction.strategy": "📌 压缩策略。\n💡 context-full=就地维护，auto-handoff=自动交接，surgical=丢弃重内容，snapcompact=图片化，off=关闭。推荐 context-full。",
    "compaction.thresholdPercent": "📌 上下文占用百分比触发压缩。\n💡 -1=使用默认。",
    "compaction.thresholdTokens": "📌 固定 token 数触发压缩（覆盖百分比设置）。\n💡 -1=使用百分比。",
    "compaction.reserveTokens": "📌 为 AI 回复预留的 token 数量。\n💡 默认 16384，一般不需要改。",
    "compaction.keepRecentTokens": "📌 始终保留的最近对话 token 数。\n💡 默认 20000，一般不需要改。",
    "compaction.autoContinue": "📌 压缩后自动继续对话。\n💡 建议开启。",
    "compaction.remoteEnabled": "📌 使用远程压缩端点而非本地摘要。\n💡 需要配置远程端点。",
    "compaction.remoteEndpoint": "📌 远程压缩服务的 URL。\n💡 一般不需要改。",
    "compaction.handoffSaveToDisk": "📌 将自动交接文档保存到 markdown 文件。\n💡 建议关闭。",
    "compaction.idleEnabled": "📌 空闲时自动压缩上下文。\n💡 适合长时间打开的会话。",
    "compaction.idleThresholdTokens": "📌 触发空闲压缩的 token 数。\n💡 默认 200000。",
    "compaction.idleTimeoutSeconds": "📌 空闲多少秒后触发压缩。\n💡 默认 300（5 分钟）。",
    "compaction.supersedeReads": "📌 缓存感知：删除同一文件的旧 read 结果。\n💡 建议开启，节省 token。",

    # SnapCompact
    "snapcompact.systemPrompt": "📌 将系统提示渲染为 PNG 图片（实验性，仅 vision 模型）。\n💡 节省 token，但失去 prompt 缓存。none=关闭。",
    "snapcompact.toolResults": "📌 将大工具结果渲染为 PNG 图片（实验性，仅 vision 模型）。\n💡 节省 token。",

    # 分支与循环
    "branchSummary.enabled": "📌 离开分支时提示总结当前工作。\n💡 建议关闭。",
    "branchSummary.reserveTokens": "📌 分支总结时预留的 token 数。\n💡 默认 16384。",
    "loop.mode": "📌 /loop 迭代之间的行为。\n💡 prompt=直接重新提交。",

    # 交互
    "steeringMode": "📌 AI 工作时如何处理排队消息。\n💡 one-at-a-time=逐个处理。",
    "followUpMode": "📌 一轮完成后如何处理后续消息。\n💡 one-at-a-time=逐个处理。",
    "interruptMode": "📌 中断消息如何影响工具执行。\n💡 immediate=立即中断。",
    "doubleEscapeAction": "📌 编辑器为空时连按两次 Esc 的行为。\n💡 tree=打开会话树。",
    "treeFilterMode": "📌 打开会话树时的默认过滤模式。\n💡 default=默认。",
    "autocompleteMaxVisible": "📌 自动补全下拉菜单最多显示的项目数。\n💡 默认 5（范围 3-20）。",

    # 记忆系统
    "memory.backend": "📌 记忆后端配置。\n💡 off=关闭，local=本地摘要，mnemopi=SQLite 本地记忆，hindsight=远程记忆。",
    "contextPromotion.enabled": "📌 上下文溢出时升级到大上下文模型而非压缩。\n💡 建议开启。",

    # MCP
    "mcp.discoveryMode": " 是否通过发现工具按需暴露 MCP 工具。\n💡 建议开启，节省 token。",
    "mcp.enableProjectConfig": "📌 是否加载项目目录下的 mcp.json。\n💡 建议开启。",
    "mcp.discoveryDefaultServers": "📌 发现模式下始终可见的 MCP 服务器。\n💡 数组类型。",
    "mcp.notifications": "📌 将 MCP 资源更新注入对话。\n💡 建议关闭，避免干扰。",
    "mcp.notificationDebounceMs": "📌 MCP 更新注入的防抖毫秒数。\n💡 默认 500。",
    "browser.enabled": " 是否启用浏览器自动化工具。\n💡 开启后 AI 可以操控网页。",
    "browser.headless": "📌 是否在后台运行浏览器（不显示界面）。\n 建议开启。",
    "browser.screenshotDir": "📌 浏览器截图的存储目录。\n💡 留空使用默认。",
    "web_search.enabled": "📌 是否启用 Web 搜索工具。\n💡 建议开启。",

    # 任务
    "task.eager": "📌 是否鼓励 AI 将工作委派给子代理。\n💡 开启后 AI 更积极用子代理并行处理任务。",
    "task.batch": "📌 一次调用派生多个独立子代理。\n💡 建议开启，提高并行效率。",
    "task.maxConcurrency": "📌 同时运行的子代理最大数量。\n💡 默认 32，一般不需要改。",
    "task.maxRecursionDepth": "📌 子代理能再派子代理的最大层数。\n💡 默认 2 层，一般不需要改。",
    "task.isolation.mode": "📌 子代理的文件系统隔离模式。\n💡 none=不隔离，auto=自动选择最佳隔离方式。",
    "task.isolation.merge": "📌 隔离任务变更的合并方式。\n💡 patch=补丁应用，branch=分支合并。",
    "task.isolation.commits": "📌 嵌套仓库变更的提交消息风格。\n💡 generic=通用，ai=AI 生成。",
    "task.enableLsp": "📌 允许子代理使用 lsp 工具。\n💡 默认关闭以保持子代理轻量。",
    "task.maxRuntimeMs": "📌 子代理最大运行时间（毫秒），0=不限制。\n💡 防止 provider 流挂起。",
    "task.agentIdleTtlMs": "📌 空闲子代理存活时间（毫秒），超时后被保存到磁盘。\n💡 默认 420000（7 分钟）。",
    "task.softRequestBudget": "📌 每个子代理的最大 API 请求数。\n💡 默认 90，超过会提醒子代理收尾。",
    "task.disabledAgents": "📌 禁用的子代理类型列表。\n💡 数组类型。",
    "task.agentModelOverrides": "📌 各子代理的专属模型配置。\n💡 字典类型。",
    "task.showResolvedModelBadge": "📌 在任务组件中显示子代理实际使用的模型。\n💡 建议关闭。",

    # Todo
    "todo.enabled": " 是否启用任务跟踪工具。\n💡 建议开启。",
    "todo.eager": "📌 是否自动创建任务列表。\n💡 建议关闭，按需创建。",
    "todo.reminders": "📌 是否在完成前提醒 AI 完成任务。\n💡 建议开启。",
    "tasks.todoClearDelay": "📌 完成或放弃的 todo 延迟多少秒后清除。\n💡 默认 60。",

    # Skills
    "skills.enabled": "📌 是否加载技能定义。\n💡 建议开启，提供专业技能能力。",
    "skills.enableSkillCommands": "📌 是否将 Skills 注册为 /skill:name 命令。\n💡 建议开启，方便直接调用。",
    "skills.enableCodexUser": "📌 加载 Codex 用户技能目录。\n💡 建议开启。",
    "skills.enableClaudeUser": "📌 加载 Claude 用户技能目录。\n💡 建议开启。",
    "skills.enableClaudeProject": "📌 加载 Claude 项目技能目录。\n💡 建议开启。",
    "skills.enablePiUser": "📌 加载 Pi 用户技能目录。\n💡 建议开启。",
    "skills.enablePiProject": "📌 加载 Pi 项目技能目录。\n💡 建议开启。",
    "skills.customDirectories": "📌 自定义技能目录路径。\n💡 数组类型。",
    "skills.ignoredSkills": "📌 忽略的技能名称列表。\n💡 数组类型。",
    "skills.includeSkills": "📌 包含的技能过滤列表（只加载匹配的技能）。\n💡 数组类型。",

    # 语音
    "stt.enabled": "📌 是否启用麦克风语音输入。\n💡 需要安装语音组件后才生效。",
    "stt.language": "📌 语音识别的语言。\n💡 zh=中文，en=英文。",
    "stt.modelName": "📌 Whisper 语音识别模型的大小。\n💡 base.en=基础版（快但不准），large=高级版（准但慢）。",

    # TTSR
    "ttsr.enabled": "📌 流式输出匹配规则时中断 AI。\n💡 Time-Traveling Stream Rules，建议开启。",
    "ttsr.contextMode": "📌 TTSR 触发时对部分输出的处理。\n💡 discard=丢弃部分输出。",
    "ttsr.interruptMode": "📌 何时中断流式输出。\n💡 always=始终中断。",
    "ttsr.repeatMode": "📌 规则可重复触发的方式。\n💡 once=每次会话只触发一次。",
    "ttsr.repeatGap": "📌 规则再次触发前需间隔的消息数。\n💡 默认 10。",
    "ttsr.builtinRules": "📌 加载 OMP 内置的默认规则。\n💡 建议开启。",
    "ttsr.disabledRules": "📌 忽略的特定规则名称。\n💡 数组类型。",

    # 启动
    "startup.quiet": "📌 开启后跳过欢迎界面。\n💡 建议关闭，保留欢迎信息。",
    "startup.checkUpdate": "📌 启动时是否检查新版本。\n💡 建议开启。",
    "startup.setupWizard": "📌 显示新增的引导步骤（每个 setup 版本一次）。\n💡 建议开启。",
    "marketplace.autoUpdate": "📌 启动时检查插件更新。\n💡 notify=通知，auto=自动更新。",
    "collapseChangelog": "📌 更新后显示压缩的变更日志。\n💡 建议开启。",
    "completion.notify": "📌 AI 完成任务后是否通知。\n💡 可选 on（开启）、off（关闭）。",
    "ask.notify": "📌 AI 等待你输入时是否通知。\n💡 可选 on（开启）、off（关闭）。",
    "ask.timeout": "📌 AI 提问后多少秒自动选择推荐选项。\n💡 0=不自动选择，手动确认。",

    # 其他
    "emojiAutocomplete": "📌 输入 :name 时是否建议 emoji。\n💡 建议开启，输入更有趣。",
    "magicKeywords.enabled": "📌 启用隐藏关键词（ultrathink/orchestrate/workflowz）。\n💡 建议开启。",
    "magicKeywords.ultrathink": "📌 启用 ultrathink 关键词触发最大自动思考。\n💡 建议开启。",
    "magicKeywords.orchestrate": "📌 启用 orchestrate 关键词触发多代理编排。\n💡 建议开启。",
    "magicKeywords.workflow": "📌 启用 workflowz 关键词触发评估工作流。\n💡 建议开启。",
    "secrets.enabled": "📌 发送给 AI 前混淆敏感信息（API key 等）。\n💡 建议开启。",
    "plan.enabled": "📌 是否启用计划模式（执行前先输出规划）。\n💡 建议开启，更可控。",
    "goal.enabled": "📌 是否启用目标模式（控制 token 预算）。\n💡 建议开启，控制成本。",
    "goal.statusInFooter": "📌 在状态栏显示 token 预算 alongside 目标指示器。\n💡 建议开启。",
    "goal.continuationModes": "📌 哪些模式下目标可自动继续。\n💡 interactive=交互模式。",

    # 认证
    "auth.broker.url": "📌 认证代理服务器 URL。\n💡 一般不需要改。",
    "auth.broker.token": "📌 认证代理 Token。\n💡 敏感信息，谨慎填写。",

    # 电源管理
    "power.preventIdleSleep": "📌 会话打开时保持系统唤醒，阻止空闲睡眠。\n💡 建议开启，防止长时间运行被打断。",
    "power.preventSystemSleep": "📌 接交流电时阻止所有系统睡眠。\n💡 仅长时间无人值守任务需要。",
    "power.declareUserActive": "📌 保持屏幕常亮，将用户视为活跃。\n💡 一般不需要。",
    "power.preventDisplaySleep": "📌 会话打开时阻止屏幕空闲睡眠。\n💡 需要屏幕常亮时开启。",

    # 模型管理
    "modelTags": "📌 给模型设置别名，方便引用。\n💡 JSON 格式，如 {\"my-fast\": \"gpt-4o-mini\"}。",
    "modelProviderOrder": "📌 控制模型提供商的显示顺序。\n💡 数组格式，一般不需要改。",
    "fastModeScope": "📌 /fast on 命令作用的提供商范围。\n💡 both=所有 / openai=仅OpenAI / claude=仅Claude。",

    # 粘贴
    "paste.largeMenuThreshold": "📌 粘贴达到此行数时弹出菜单（代码块/XML/保存文件）。\n💡 默认 100，0=禁用菜单。",

    # 协作 & 分享
    "collab.relayUrl": "📌 /collab 协作功能使用的中继服务器。\n💡 默认 wss://my.omp.sh。",
    "collab.displayName": "📌 协作中显示给其他参与者的名称。\n💡 留空则用操作系统用户名。",
    "share.serverUrl": "📌 /share 分享功能的查看/上传服务器。\n💡 默认 https://my.omp.sh/s。",
    "share.redactSecrets": "📌 分享快照上传前自动混淆敏感信息。\n💡 建议开启。",

    # 上下文压缩增强
    "compaction.dropUseless": "📌 自动剪除标记为无用的工具结果（无匹配、超时等）。\n💡 建议开启，节省 token。",

    # SnapCompact
    "snapcompact.shape": "📌 SnapCompact 打印文本的框架形状。\n💡 auto=自动为当前模型优化。",

    # 记忆系统
    "memories.enabled": "📌 启用记忆系统。\n💡 实验性功能，一般不需要。",
    "memories.maxRolloutsPerStartup": "📌 每次启动最大记忆展开次数。\n💡 默认 64。",
    "memories.maxRolloutAgeDays": "📌 记忆展开最大存活天数。\n💡 默认 30。",
    "memories.minRolloutIdleHours": "📌 最小空闲小时后展开记忆。\n💡 默认 12。",
    "memories.threadScanLimit": "📌 线程扫描上限。\n💡 默认 300。",
    "memories.maxRawMemoriesForGlobal": "📌 全局搜索最大原始记忆数。\n💡 默认 200。",
    "memories.stage1Concurrency": "📌 阶段1并发数。\n💡 默认 8。",
    "memories.stage1LeaseSeconds": "📌 阶段1租约秒数。\n💡 默认 120。",
    "memories.stage1RetryDelaySeconds": "📌 阶段1重试延迟秒数。\n💡 默认 120。",
    "memories.phase2LeaseSeconds": "📌 阶段2租约秒数。\n💡 默认 180。",
    "memories.phase2RetryDelaySeconds": "📌 阶段2重试延迟秒数。\n💡 默认 180。",
    "memories.phase2HeartbeatSeconds": "📌 阶段2心跳秒数。\n💡 默认 30。",
    "memories.rolloutPayloadPercent": "📌 展开负载百分比。\n💡 默认 0.7。",
    "memories.phase1InputTokenLimit": "📌 阶段1输入 token 限制。\n💡 默认 4000。",
    "memories.fallbackTokenLimit": "📌 回退 token 限制。\n💡 默认 16000。",
    "memories.summaryInjectionTokenLimit": "📌 摘要注入 token 限制。\n💡 默认 5000。",

    # Mnemopi 本地记忆
    "mnemopi.dbPath": "📌 Mnemopi SQLite 数据库路径。\n💡 留空则使用默认路径。",
    "mnemopi.bank": "📌 共享库基础名称。\n💡 一般不需要。",
    "mnemopi.scoping": "📌 Mnemopi 记忆作用域。\n💡 per-project=每项目隔离，推荐。",
    "mnemopi.embeddingVariant": "📌 嵌入模型变体。\n💡 en=英语优先，multilingual=跨语言。",
    "mnemopi.autoRecall": "📌 每轮会话首轮自动回忆本地记忆。\n💡 建议开启，让 AI 记住之前的经验。",
    "mnemopi.autoRetain": "📌 完成的对话自动存入记忆。\n💡 建议开启。",
    "mnemopi.polyphonicRecall": "📌 启用 4 声部回忆（向量/图/事实/时间）融合。\n💡 实验性，需要更多资源。",
    "mnemopi.enhancedRecall": "📌 启用分层查询结果缓存。\n💡 重复查询时节省 token。",
    "mnemopi.noEmbeddings": "📌 强制仅用 FTS（全文搜索）回忆，不用向量嵌入。\n💡 一般不需要。",
    "mnemopi.embeddingModel": "📌 显式嵌入模型 ID，覆盖 variant 设置。\n💡 高级选项。",
    "mnemopi.embeddingApiUrl": "📌 OpenAI 兼容的嵌入 API 端点。\n💡 使用远程嵌入时填写。",
    "mnemopi.embeddingApiKey": "📌 嵌入 API 密钥。\n💡 敏感信息。",
    "mnemopi.llmMode": "📌 Mnemopi LLM 模式。\n💡 smol=使用小型模型，recommended。",
    "mnemopi.llmBaseUrl": "📌 远程 LLM 端点。\n💡 remote 模式时填写。",
    "mnemopi.llmApiKey": "📌 远程 LLM 密钥。\n💡 敏感信息。",
    "mnemopi.llmModel": "📌 远程 LLM 模型名。\n💡 remote 模式时填写。",
    "mnemopi.retainEveryNTurns": "📌 每 N 轮对话自动保留到记忆。\n💡 默认 4。",
    "mnemopi.recallLimit": "📌 每次回忆条数上限。\n💡 默认 8。",
    "mnemopi.recallContextTurns": "📌 回忆附带上下文轮数。\n💡 默认 3。",
    "mnemopi.recallMaxQueryChars": "📌 回忆查询最大字符数。\n💡 默认 4000。",
    "mnemopi.injectionTokenLimit": "📌 注入记忆的 token 限制。\n💡 默认 5000。",
    "mnemopi.debug": "📌 Mnemopi 调试模式。\n💡 开发时使用。",

    # Hindsight 远程记忆
    "hindsight.apiUrl": "📌 Hindsight 远程记忆服务器 URL。\n💡 默认 http://localhost:8888。",
    "hindsight.apiToken": "📌 Hindsight API Token。\n💡 敏感信息。",
    "hindsight.bankId": "📌 Hindsight 记忆库 ID。\n💡 留空则用项目名。",
    "hindsight.bankIdPrefix": "📌 Hindsight 记忆库 ID 前缀。\n💡 一般不需要。",
    "hindsight.scoping": "📌 Hindsight 作用域。\n💡 per-project-tagged=全局可见+项目隔离写入。",
    "hindsight.bankMission": "📌 Hindsight 记忆库使命提示。\n💡 引导 AI 记忆的重点。",
    "hindsight.retainMission": "📌 Hindsight 保留使命提示。\n💡 引导 AI 保留什么内容。",
    "hindsight.autoRecall": "📌 首轮会话自动从 Hindsight 回忆。\n💡 建议开启。",
    "hindsight.autoRetain": "📌 每 N 轮+会话边界自动保留到 Hindsight。\n💡 建议开启。",
    "hindsight.retainMode": "📌 Hindsight 保留模式。\n💡 full-session=整会话一条文档。",
    "hindsight.retainEveryNTurns": "📌 Hindsight 每 N 轮保留。\n💡 默认 3。",
    "hindsight.retainOverlapTurns": "📌 Hindsight 保留重叠轮数。\n💡 默认 2，保持上下文连续。",
    "hindsight.retainContext": "📌 Hindsight 保留上下文。\n💡 默认 omp。",
    "hindsight.recallBudget": "📌 Hindsight 回忆预算。\n💡 mid=中等。",
    "hindsight.recallMaxTokens": "📌 Hindsight 回忆最大 token。\n💡 默认 1024。",
    "hindsight.recallContextTurns": "📌 Hindsight 回忆上下文轮数。\n💡 默认 1。",
    "hindsight.recallMaxQueryChars": "📌 Hindsight 回忆查询最大字符。\n💡 默认 800。",
    "hindsight.recallTypes": "📌 Hindsight 回忆类型。\n💡 [\"world\", \"experience\"]。",
    "hindsight.debug": "📌 Hindsight 调试模式。\n💡 开发时使用。",
    "hindsight.mentalModelsEnabled": "📌 加载心智模型到开发指令。\n💡 建议开启，让 AI 理解项目惯例。",
    "hindsight.mentalModelAutoSeed": "📌 自动创建内置心智模型种子。\n💡 建议开启。",
    "hindsight.mentalModelRefreshIntervalMs": "📌 心智模型刷新间隔（毫秒）。\n💡 默认 300000（5 分钟）。",
    "hindsight.mentalModelMaxRenderChars": "📌 心智模型最大渲染字符。\n💡 默认 16000。",

    # 自动学习
    "autolearn.enabled": "📌 AI 停止后自动捕获经验到记忆和技能。\n💡 实验性，按需开启。",
    "autolearn.autoContinue": "📌 自动运行一轮捕获（消耗额外 token）。\n💡 开启后更自动，但耗 token。",
    "autolearn.minToolCalls": "📌 最少工具调用数触发自动学习。\n💡 默认 5。",

    # Bash 增强
    "bashInterceptor.patterns": "📌 Bash 拦截的正则规则列表。\n💡 拦截错误命令并提示使用正确工具。",
    "bash.stripTrailingHeadTail": "📌 静默丢弃 bash 命令尾部的 | head/tail 管道。\n💡 建议开启，OMP 已自动截断输出。",

    # Shell 压缩
    "shellMinimizer.enabled": "📌 压缩 shell 输出（git/npm/cargo 等）。\n💡 建议开启，节省 token。",
    "shellMinimizer.settingsPath": "📌 Shell 压缩自定义设置路径。\n💡 留空用默认。",
    "shellMinimizer.only": "📌 白名单：仅压缩这些命令。\n💡 数组格式，如 [\"npm\", \"cargo\"]。",
    "shellMinimizer.except": "📌 排除：不压缩这些命令。\n💡 数组格式。",
    "shellMinimizer.maxCaptureBytes": "📌 Shell 输出最大捕获字节数。\n💡 默认 4194304（4MB）。",
    "shellMinimizer.sourceOutlineLevel": "📌 源码大纲模式。\n💡 default / aggressive。",
    "shellMinimizer.legacyFilters": "📌 旧版过滤器兼容模式。\n💡 一般不需要。",

    # Eval
    "eval.py": "📌 允许 eval 工具执行 Python 代码。\n💡 建议开启。",
    "eval.js": "📌 允许 eval 工具执行 JavaScript 代码。\n💡 建议开启。",

    # Python
    "python.kernelMode": "📌 Python 内核模式。\n💡 session=保持活跃（推荐），fresh=每次新建。",
    "python.interpreter": "📌 Python 解释器路径，覆盖自动发现。\n💡 留空用自动发现。",

    # 工具审批增强
    "tools.approval": "📌 逐工具审批策略。\n💡 JSON 格式，如 {\"bash\": \"allow\", \"write\": \"prompt\"}。",

    # Todo 增强
    "todo.reminders.max": "📌 Todo 提醒最大次数。\n💡 默认 3。",
    "todo.eager": "📌 自动创建 Todo 的积极程度。\n💡 default=默认。",

    # AST 工具
    "astGrep.enabled": "📌 启用 ast_grep：AST 结构搜索。\n💡 建议开启，代码搜索更精准。",
    "astEdit.enabled": "📌 启用 ast_edit：AST 结构重写。\n💡 建议开启，代码修改更安全。",

    # 工具扩展
    "renderMermaid.enabled": "📌 启用 Mermaid 图渲染为 ASCII。\n💡 按需开启。",
    "debug.enabled": "📌 启用 DAP 调试工具。\n💡 开发调试时需要。",
    "speechgen.enabled": "📌 启用 TTS 语音文件合成。\n💡 按需开启。",
    "inspect_image.enabled": "📌 启用图片理解工具。\n💡 按需开启。",
    "checkpoint.enabled": "📌 启用上下文检查点/回退工具。\n💡 需要回退对话时开启。",
    "fetch.enabled": "📌 允许 read 工具获取 URL 内容。\n💡 建议开启。",
    "vault.enabled": "📌 启用 Obsidian vault:// 内容读取。\n💡 使用 Obsidian 时开启。",
    "github.enabled": "📌 启用 GitHub 工具。\n💡 需要操作 GitHub 时开启。",
    "github.cache.enabled": "📌 GitHub issue/PR 视图缓存。\n💡 建议开启，减少 API 调用。",
    "github.cache.softTtlSec": "📌 GitHub 缓存软过期时间（秒）。\n💡 默认 300（5 分钟）。",
    "github.cache.hardTtlSec": "📌 GitHub 缓存硬过期时间（秒）。\n💡 默认 604800（7 天）。",

    # 异步
    "async.enabled": "📌 启用异步 bash 和后台任务执行。\n💡 建议开启。",
    "async.maxJobs": "📌 最大后台任务数。\n💡 默认 100。",
    "async.pollWaitDuration": "📌 Poll 等待时长策略。\n💡 smart=自适应（推荐）。",

    # IRC
    "irc.timeoutMs": "📌 IRC 等待默认超时（毫秒）。\n💡 默认 120000（2 分钟），0=不超时。",

    # 工具发现
    "tools.discoveryMode": "📌 工具发现/隐藏模式。\n💡 auto=超过 40 工具时隐藏 MCP。",

    # Skills 新增
    "skills.enableAgentsUser": "📌 加载 Codex/Agents 用户技能。\n💡 建议开启。",
    "skills.enableAgentsProject": "📌 加载 Codex/Agents 项目技能。\n💡 建议开启。",

    # Commands
    "commands.enableClaudeUser": "📌 加载 ~/.claude/commands/ 命令。\n💡 兼容 Claude Code 命令。",
    "commands.enableClaudeProject": "📌 加载 .claude/commands/ 命令。\n💡 兼容 Claude Code 项目命令。",
    "commands.enableOpencodeUser": "📌 加载 ~/.config/opencode/commands/ 命令。\n💡 兼容 Opencode 命令。",
    "commands.enableOpencodeProject": "📌 加载 .opencode/commands/ 命令。\n💡 兼容 Opencode 项目命令。",

    # 提供商配置
    "providers.webSearch": "📌 Web 搜索首选提供商。\n💡 auto=自动选择。",
    "providers.image": "📌 图片生成首选提供商。\n💡 auto=自动选择。",
    "providers.tts": "📌 TTS 后端。\n💡 auto / kokoro（本地） / xai（xAI Grok Voice）。",
    "tts.localModel": "📌 本地 TTS 模型。\n💡 kokoro=默认。",
    "tts.localVoice": "📌 本地 TTS 语音。\n💡 af_heart=默认英文女声。",

    # 语音输出
    "speech.enabled": "📌 流式输出时朗读 AI 回复。\n💡 需要语音反馈时开启。",
    "speech.mode": "📌 朗读内容范围。\n💡 assistant=仅消息（推荐）。",
    "speech.voice": "📌 朗读使用的语音。\n💡 af_heart=默认英文女声。",

    # 提供商模型
    "providers.tinyModel": "📌 会话标题模型来源。\n💡 online=在线小型模型（推荐）。",
    "providers.tinyModelDevice": "📌 TinyModel ONNX 执行设备。\n💡 default=CPU。",
    "providers.tinyModelDtype": "📌 TinyModel ONNX 量化精度。\n💡 default=模型自带（q4）。",
    "providers.memoryModel": "📌 Mnemopi 记忆 LLM 来源。\n💡 online=在线小型模型。",
    "providers.autoThinkingModel": "📌 自动思考难度分类模型。\n💡 online=在线小型模型。",
    "providers.kimiApiFormat": "📌 Kimi Code API 格式。\n💡 anthropic=Anthropic 兼容格式。",
    "providers.openaiWebsockets": "📌 OpenAI WebSocket 策略。\n💡 auto=使用模型默认。",
    "providers.openrouterVariant": "📌 OpenRouter 路由变体后缀。\n💡 default=默认。",
    "providers.fetch": "📌 URL 读取后端优先级。\n💡 auto=自动选择。",

    # Provider 缓存
    "provider.appendOnlyContext": "📌 追加-only 上下文缓存策略。\n💡 auto=已知支持的提供商自动开启。",

    # Codex 重置
    "codexResets.autoRedeem": "📌 Codex 周限额自动兑换策略。\n💡 unset=首次询问 / yes=自动 / no=禁用。",
    "codexResets.minBlockedMinutes": "📌 自动兑换最小阻塞分钟。\n💡 默认 60。",
    "codexResets.keepCredits": "📌 保留信用额度，不自动低于此数。\n💡 默认 0。",

    # Exa 搜索
    "exa.enabled": "📌 Exa 搜索总开关。\n💡 建议开启，提供高质量搜索结果。",
    "exa.enableSearch": "📌 Exa 基本/深度/代码搜索。\n💡 建议开启。",
    "exa.enableResearcher": "📌 Exa 深度研究工具。\n💡 需要深度调研时开启。",
    "exa.enableWebsets": "📌 Exa 数据集管理。\n💡 一般不需要。",

    # SearXNG
    "searxng.endpoint": "📌 SearXNG 自托管实例 URL。\n💡 自建搜索服务时填写。",
    "searxng.token": "📌 SearXNG Token。\n💡 敏感信息。",
    "searxng.basicUsername": "📌 SearXNG 用户名。\n💡 基本认证时使用。",
    "searxng.basicPassword": "📌 SearXNG 密码。\n💡 敏感信息。",
    "searxng.categories": "📌 SearXNG 搜索分类。\n💡 如 general,news,science。",
    "searxng.language": "📌 SearXNG 搜索语言。\n💡 如 zh=中文，en=英文。",

    # Commit
    "commit.mapReduceEnabled": "📌 Commit 消息 map-reduce 模式。\n💡 大变更时拆分生成更精准的提交消息。",
    "commit.mapReduceMinFiles": "📌 触发 map-reduce 的最小文件数。\n💡 默认 4。",
    "commit.mapReduceMaxFileTokens": "📌 单文件最大 token 数。\n💡 默认 50000。",
    "commit.mapReduceTimeoutMs": "📌 map-reduce 超时（毫秒）。\n💡 默认 120000（2 分钟）。",
    "commit.mapReduceMaxConcurrency": "📌 map-reduce 最大并发数。\n💡 默认 5。",
    "commit.changelogMaxDiffChars": "📌 Changelog 最大差异字符数。\n💡 默认 120000。",

    # Auto QA
    "dev.autoqa": "📌 自动 QA：工具问题自动报告。\n💡 开发/测试时开启。",
    "dev.autoqaPush.endpoint": "📌 Auto QA 报告端点。\n💡 默认 https://qa.omp.sh/v1/grievances。",
    "dev.autoqaPush.token": "📌 Auto QA 报告 Token。\n💡 敏感信息。",
    "dev.autoqa.consent": "📌 Auto QA 同意状态。\n💡 unset=首次询问 / yes=同意 / no=拒绝。",

    # MCP & Browser 新增
    "browser.cmux": "📌 使用 cmux WKWebView 进行浏览器自动化。\n💡 有 cmux socket 时自动启用。",

    # 内部/高级
    "extensions": "📌 已安装的扩展列表。\n💡 JSON 数组格式。",
    "enabledModels": "📌 已启用的模型列表。\n💡 JSON 数组格式。",
    "disabledProviders": "📌 已禁用的提供商列表。\n💡 JSON 数组格式。",
    "disabledExtensions": "📌 已禁用的扩展列表。\n💡 JSON 数组格式。",
    "setupVersion": "📌 安装版本号。\n💡 OMP 内部使用。",
}

DEFAULT_HINT = "📌 这是一个 OMP 配置项。\n💡 如果不确定怎么改，保持默认即可。"


def get_omp_config():
    result = subprocess.run(
        ["omp", "config", "list", "--json"],
        capture_output=True, text=True, timeout=30,
        encoding="utf-8", errors="replace",
        creationflags=subprocess.CREATE_NO_WINDOW)
    if result.returncode != 0:
        return None, None, result.stderr
    raw = json.loads(result.stdout)
    flat = {}
    for k, v in raw.items():
        if isinstance(v, dict) and "value" in v:
            flat[k] = v["value"]
        else:
            flat[k] = v
    return flat, raw, None


def set_omp_config(key, value):
    result = subprocess.run(
        ["omp", "config", "set", key, val_str],
        capture_output=True, text=True, timeout=10,
        encoding="utf-8", errors="replace",
        creationflags=subprocess.CREATE_NO_WINDOW)
    return result.returncode == 0, result.stderr


class OMPConfigApp:
    def __init__(self, root):
        self.root = root
        self.root.title("OMP 配置管理器")
        self.root.geometry("1050x680")
        self.root.configure(bg="#f5f5f5")
        self.config = {}
        self._raw_config = {}
        self.modified_keys = set()

        top = tk.Frame(root, bg="#2c3e50", height=50)
        top.pack(fill=tk.X)
        top.pack_propagate(False)
        tk.Label(top, text="OMP 配置管理器  |  业务人员专用",
                 font=("Microsoft YaHei", 14, "bold"),
                 bg="#2c3e50", fg="#ecf0f1").pack(pady=8)
        tk.Label(root, text="双击行可编辑  |  修改后点击「保存」，重启 OMP 生效",
                 fg="#999", font=("Microsoft YaHei", 9)
                 ).pack(anchor=tk.W, padx=14, pady=(4, 0))

        main = tk.Frame(root, bg="#f5f5f5")
        main.pack(fill=tk.BOTH, expand=True, padx=10, pady=6)

        left = tk.Frame(main, bg="#f5f5f5", width=210)
        left.pack(side=tk.LEFT, fill=tk.Y)
        left.pack_propagate(False)
        self.cat_tree = ttk.Treeview(left, show="tree", height=20)
        self.cat_tree.pack(fill=tk.Y, expand=True)
        self.cat_tree.bind("<<TreeviewSelect>>", self._on_category_select)

        right = tk.Frame(main, bg="#f5f5f5")
        right.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        sf = tk.Frame(right, bg="#f5f5f5")
        sf.pack(fill=tk.X, pady=(0, 4))
        tk.Label(sf, text="🔍", bg="#f5f5f5").pack(side=tk.LEFT)
        self.search_var = tk.StringVar()
        self.search_var.trace_add("write", self._on_search)
        tk.Entry(sf, textvariable=self.search_var, width=28, font=("Microsoft YaHei", 10)
                 ).pack(side=tk.LEFT, padx=4)

        # === 右侧区域：Treeview + 滚动条 ===
        tvf = tk.Frame(right, bg="#f5f5f5")
        tvf.pack(fill=tk.BOTH, expand=True)
        self.tree = ttk.Treeview(tvf, columns=("key","desc","value","edit"), show="headings", height=18)
        self.tree.heading("key", text="配置项")
        self.tree.heading("desc", text="说明")
        self.tree.heading("value", text="当前值")
        self.tree.heading("edit", text="编辑")
        self.tree.column("key", width=220, anchor=tk.W, minwidth=180)
        self.tree.column("desc", width=350, anchor=tk.W, minwidth=200)
        self.tree.column("value", width=130, anchor=tk.W, minwidth=80)
        self.tree.column("edit", width=120, anchor=tk.CENTER, minwidth=80)
        self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        # 滚动条（和密钥管理器一样的简单 ttk.Scrollbar）
        sb = ttk.Scrollbar(tvf, orient=tk.VERTICAL, command=self.tree.yview)
        self.tree.configure(yscrollcommand=sb.set)
        sb.pack(side=tk.RIGHT, fill=tk.Y)
        self.tree.bind("<Double-1>", self._on_double_click)

        bar = tk.Frame(root, bg="#f5f5f5")
        bar.pack(fill=tk.X, padx=10, pady=(4, 6))
        tk.Button(bar, text="保存所有修改", command=self.save_all,
                  bg="#27ae60", fg="white", font=("Microsoft YaHei", 11, "bold"),
                  bd=0, relief=tk.FLAT, cursor="hand2", padx=14, pady=6
                  ).pack(side=tk.LEFT)
        self.save_status = tk.StringVar(value="就绪")
        tk.Label(bar, textvariable=self.save_status, bg="#f5f5f5",
                 fg="#666", font=("Microsoft YaHei", 9)
                 ).pack(side=tk.LEFT, padx=10)

        self.load_config()



    def load_config(self):
        self.config, self._raw_config, err = get_omp_config()
        if err:
            messagebox.showerror("错误", "读取 OMP 配置失败:\n{}".format(err))
            return
        for item in self.cat_tree.get_children():
            self.cat_tree.delete(item)
        for cat in CATEGORY_GROUPS:
            self.cat_tree.insert("", tk.END, iid=cat, text=cat)
        self._show_all()
        self.cat_tree.selection_set(" 所有配置")
    def _on_category_select(self, event):
        sel = self.cat_tree.selection()
        if not sel:
            return
        cat = sel[0]
        if cat == " 所有配置":
            self._show_all()
        else:
            keys = CATEGORY_GROUPS.get(cat)
            if keys:
                self._show_keys(keys)

    def _show_all(self):
        self._show_keys(sorted(self.config.keys()))

    def _show_keys(self, keys):
        for item in self.tree.get_children():
            self.tree.delete(item)
        for key in keys:
            if key not in self.config:
                continue
            value = self.config[key]
            desc = CONFIG_DESC_ZH.get(key, "")
            if isinstance(value, bool):
                val_str = "✅ 已启用" if value else " 已禁用"
                edit_str = " 点击切换"
            elif isinstance(value, (int, float)):
                val_str = str(value)
                edit_str = " 点击编辑"
            elif isinstance(value, (list, dict)):
                val_str = json.dumps(value, ensure_ascii=False)[:25]
                edit_str = " 点击编辑"
            else:
                val_str = str(value)[:25]
                edit_str = " 点击编辑"
            self.tree.insert("", tk.END, iid=key, values=(key, desc, val_str, edit_str))

    def _on_search(self, *args):
        q = self.search_var.get().strip().lower()
        if not q:
            self._show_all()
            return
        results = [k for k in sorted(self.config.keys())
                   if q in k.lower() or q in CONFIG_DESC_ZH.get(k, "").lower()]
        self._show_keys(results)

    def _on_double_click(self, event):
        sel = self.tree.selection()
        if not sel:
            return
        key = sel[0]
        value = self.config[key]
        new_val = self._edit_dialog(key, value)
        if new_val is not None:
            self.config[key] = new_val
            self.modified_keys.add(key)
            self._show_keys(sorted(self.config.keys()))

    def _edit_dialog(self, key, value):
        zh_desc = CONFIG_DESC_ZH.get(key, "")
        hint = HINT_TEXT.get(key, DEFAULT_HINT)

        dlg = tk.Toplevel(self.root)
        dlg.title("编辑: " + key)
        dlg.geometry("540x440")
        dlg.transient(self.root)
        dlg.grab_set()
        dlg.configure(bg="#f9f9f9")

        title_bg = tk.Frame(dlg, bg="#e8f4f8")
        title_bg.pack(fill=tk.X)
        tk.Label(title_bg, text=key, font=("Consolas", 11, "bold"),
                 bg="#e8f4f8", fg="#2c3e50").pack(anchor=tk.W, padx=12, pady=(8, 0))
        if zh_desc:
            tk.Label(title_bg, text=zh_desc, font=("Microsoft YaHei", 9),
                     bg="#e8f4f8", fg="#555").pack(anchor=tk.W, padx=12, pady=(2, 8))

        hint_bg = tk.Frame(dlg, bg="#fffbe6", bd=1, relief=tk.SOLID)
        hint_bg.pack(fill=tk.X, padx=12, pady=(0, 8))
        tk.Label(hint_bg, text=hint, font=("Microsoft YaHei", 9),
                 bg="#fffbe6", fg="#666", justify=tk.LEFT, wraplength=500
                 ).pack(padx=10, pady=8)

        if isinstance(value, bool):
            var = tk.BooleanVar(value=value)
            frame = tk.Frame(dlg, bg="#f9f9f9")
            frame.pack(pady=8)
            tk.Label(frame, text="当前状态：", font=("Microsoft YaHei", 10),
                     bg="#f9f9f9").pack(side=tk.LEFT, padx=4)
            cb = ttk.Checkbutton(frame, text="已启用", variable=var, font=("Microsoft YaHei", 10))
            cb.pack(side=tk.LEFT, padx=4)
            btn_frame = tk.Frame(dlg, bg="#f9f9f9")
            btn_frame.pack(pady=10)
            tk.Button(btn_frame, text="  确定  ", command=lambda: self._ok_dialog(dlg, var.get()),
                      bg="#27ae60", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)
            tk.Button(btn_frame, text="  取消  ", command=dlg.destroy,
                      bg="#95a5a6", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)
        elif isinstance(value, (int, float)):
            var = tk.StringVar(value=str(value))
            tk.Label(dlg, text="请输入数值：", font=("Microsoft YaHei", 10),
                     bg="#f9f9f9").pack(pady=8)
            tk.Entry(dlg, textvariable=var, width=30, font=("Consolas", 11)).pack(pady=4)
            btn_frame = tk.Frame(dlg, bg="#f9f9f9")
            btn_frame.pack(pady=10)
            tk.Button(btn_frame, text="  确定  ", command=lambda: self._ok_numeric(dlg, var, type(value)),
                      bg="#27ae60", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)
            tk.Button(btn_frame, text="  取消  ", command=dlg.destroy,
                      bg="#95a5a6", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)
        else:
            var = tk.Text(dlg, width=55, height=8, font=("Consolas", 10), wrap=tk.WORD)
            var.insert("1.0", json.dumps(value, ensure_ascii=False, indent=2))
            var.pack(padx=12, pady=8, fill=tk.BOTH, expand=True)
            btn_frame = tk.Frame(dlg, bg="#f9f9f9")
            btn_frame.pack(pady=6)
            tk.Button(btn_frame, text="  确定  ", command=lambda: self._ok_json(dlg, var),
                      bg="#27ae60", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)
            tk.Button(btn_frame, text="  取消  ", command=dlg.destroy,
                      bg="#95a5a6", fg="white", font=("Microsoft YaHei", 11, "bold"),
                      bd=0, relief=tk.FLAT, cursor="hand2", padx=12, pady=6).pack(side=tk.LEFT, padx=6)

        dlg.result = None
        dlg.wait_window()
        return dlg.result

    def _ok_dialog(self, dlg, value):
        dlg.result = value
        dlg.destroy()

    def _ok_numeric(self, dlg, var, val_type):
        try:
            val = val_type(var.get())
            dlg.result = val
            dlg.destroy()
        except ValueError:
            messagebox.showwarning("提示", "请输入有效的数值")

    def _ok_json(self, dlg, text_widget):
        try:
            val = json.loads(text_widget.get("1.0", tk.END).strip())
            dlg.result = val
            dlg.destroy()
        except json.JSONDecodeError:
            messagebox.showwarning("提示", "JSON 格式不正确")

    def save_all(self):
        if not self.modified_keys:
            self.save_status.set("没有需要保存的修改")
            return
        msg = "确定保存 {} 项修改？\n\n重启 OMP 后生效".format(len(self.modified_keys))
        ok = messagebox.askyesno("确认", msg)
        if not ok:
            return
        saved = 0
        errors = []
        for key in self.modified_keys:
            success, err = set_omp_config(key, self.config[key])
            if success:
                saved += 1
            else:
                errors.append("{}: {}".format(key, err))
        self.modified_keys.clear()
        if errors:
            messagebox.showwarning("部分保存失败", "\n".join(errors))
        self.save_status.set("已保存 {}/{} 项".format(saved, len(self.config)))

if __name__ == "__main__":
    root = tk.Tk()
    OMPConfigApp(root)
    root.mainloop()


